# -----------------------
# ~/.config/starship.toml
# -----------------------

# add_newline = false      # Inserts blank line between shell prompts. Default = true
# command_timeout = 500    # Timeout for commands executed by starship (in milliseconds).
# scan_timeout = 30        # Timeout for starship to scan files (in milliseconds).

format="""
$os\
[(î‚¶\
$time\
$battery\
î‚´ )](bgcolor1)\
$cmd_duration\
$kubernetes\
$aws\
$gcloud\
$azure\
$line_break\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill \
$all\
$shlvl\
$shell\
$line_break\
$status\
$character\
"""

right_format="""
[(î‚¶\
$username\
$hostname\
$localip\
î‚´)](bgcolor2)\
"""

# -----------------------
# COLOR PALETTE
# -----------------------
palette = "custom1"

[palettes.custom1]
# white = '#ffffff'
# black = '#000000'
# bgcolor1 = 'none'
# bgcolor2 = 'none'
bgcolor1 = 'black'
bgcolor2 = 'bright-black'
ubuntu_orange = '#E95420'
ubuntu_light_aubergine = '#77216F'
ubuntu_mid_aubergine = '#5E2750'
ubuntu_dark_aubergine = '#2C001E'
ubuntu_warm_grey = '#AEA79F'
ubuntu_cool_grey = '#333333'
ubuntu_text_grey = '#111111'
canonical_aubergine = '#772953'

# -----------------------
# MODULES
# -----------------------

[aws]
disabled = false
format = 'on [$symbol($profile )[(\($region\) )]($style dimmed)(\[$duration\])]($style) '
# format = '([î‚¶](bgcolor)[$symbol($profile )[(\($region\) )]($style dimmed)(\[$duration\])]($style)[î‚´](bgcolor) )'
# style = 'bold yellow bg:bgcolor'
symbol = 'ï‰° '

[azure]
disabled = false
# format = 'on [$symbol($subscription)]($style) '
# format = '([î‚¶](bgcolor)[$symbol($subscription)]($style)[î‚´](bgcolor) )'
# style = 'bold blue bg:bgcolor'
symbol = 'î¯˜ '

[battery]
format = '[ $symbol$percentage]($style bg:bgcolor1)'
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[[battery.display]]
threshold = 99

[character]
format = '$symbol '
# success_symbol = '[ï”](bold green)'
# error_symbol = '[ï”](bold red)'
# success_symbol = '[â¯](bold green)'
# error_symbol = '[â¯](bold red)'

[directory]
# truncation_length = 8
truncation_symbol = 'â€¦/'
# style = 'bold cyan italic'
home_symbol = 'ï€• ~'

[docker_context]
only_with_files = false

[fill]
symbol = ' '
style= 'dimmed white'

[gcloud]
disabled = true
format = 'on [$symbol($project )[\($region\)]($style dimmed)]($style) '
# format = 'on [$symbol($account(@$domain) )[(\($region\) \($project\))]($style dimmed)]($style) '
# format = '([î‚¶](bgcolor)[$symbol($account(@$domain) )[(\($region\) \($project\))]($style dimmed)]($style)[î‚´](bgcolor) )'
# style = 'bold blue bg:bgcolor'
symbol = 'ï†  '

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style bg:bgcolor2)'
# format = '[@$ssh_symbol$hostname ]($style)'
style = 'bright-green'

[kubernetes]
disabled = false
format = '[$symbol$context[( \($namespace\))]($style dimmed)]($style) '
# format = '[$symbol$context( \($namespace\))]($style) in '
style = 'bold green'
symbol = 'âˆ '
# symbol = 'ï´± '
# symbol = 'â˜¸ï¸'

[kubernetes.context_aliases]
'.*cluster/(.*)' = '$1'

[localip]
ssh_only = false
disabled = false
# format = '([î‚¶](bgcolor)[$localipv4]($style bg:bgcolor)[î‚´](bgcolor) )'
format = '[ [\[](bg:bgcolor2)$localipv4[\]](bg:bgcolor2)]($style bg:bgcolor2)'
# format = '[\[$localipv4\]]($style) '
style = 'cyan italic'

[os]
format = '[$symbol ]($style)'
# format = '[$symbol ]($style bg:bgcolor1)'
# style = 'bold ubuntu_orange'
disabled = false

[os.symbols]
Alpine = 'ïŒ€ '
Arch = 'ïŒƒ '
CentOS = 'ïŒ„ '
Debian = 'î½ '
Fedora = 'ïŒŠ '
Gentoo = 'ïŒ '
Linux = 'ï…¼ '
Macos = 'ï”´ '
Manjaro = 'ïŒ’ '
NixOS = 'ïŒ“ '
openSUSE = 'ïŒ” '
Raspbian = 'ïŒ• '
RedHatEnterprise = 'ïŒ– '
Ubuntu = 'ïŒ› '
Windows = 'î˜ª '

[shell]
disabled = false
fish_indicator = 'ğŸŸ'
bash_indicator = 'î¯Š '
# zsh_indicator = 'ğŸš€'
zsh_indicator = 'ğŸ’¤'
powershell_indicator = 'î¯‡ '
unknown_indicator = 'ïŠœ '
# format  = '[$indicator ]($style bg:bgcolor1)'
# format  = '[$indicator]($style)'

[shlvl]
disabled = false
# format = '[$symbol]($style)'
# format = '[$symbol$shlvl ]($style bg:bgcolor2)'
# symbol = 'ï”'
# symbol = 'â¯'
# symbol = 'ï…‰'
symbol = 'â†•'
# repeat = true
# threshold = 1
style = 'dimmed white'

[status]
disabled = false
symbol = 'ïª '
# symbol = 'ï€ '
map_symbol = true
pipestatus = true

[time]
disabled = false
format = '[ï€— $time]($style bg:bgcolor1)'
style = 'bold bright-yellow'

[username]
show_always = true
format = '[$user[@](bg:bgcolor2)]($style bg:bgcolor2)'
# format = '[$user]($style)'
style_user = 'bright-yellow'
