# -----------------------
# ~/.config/starship.toml
# -----------------------

# add_newline = false      # Inserts blank line between shell prompts. Default = true
# command_timeout = 500    # Timeout for commands executed by starship (in milliseconds).
# scan_timeout = 30        # Timeout for starship to scan files (in milliseconds).

format="""
$all\
$fill \
[(î‚¶\
$os\
$username\
$hostname\
$localip\
$shell\
î‚´) ](bgcolor2)\
$line_break\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$shlvl\
$status\
$character\
"""
# $fill\
# $cmd_duration\
# $kubernetes\

right_format="""
[(î‚¶\
$battery\
$time\
î‚´) ](bgcolor1)\
"""
# $aws\
# $gcloud\
# $azure\

# -----------------------
# COLOR PALETTE
# -----------------------
palette = "custom1"

[palettes.custom1]
# white = '#ffffff'
# black = '#000000'
bgcolor1 = 'black'
bgcolor2 = 'bright-black'
ubuntu_orange = '#E95420'
ubuntu_light_aubergine = '#77216F'
ubuntu_mid_aubergine = '#5E2750'
ubuntu_dark_aubergine = '#2C001E'
ubuntu_warm_grey = '#AEA79F'
ubuntu_cool_grey = '#333333'
ubuntu_text_grey = '#111111'
canonical_aubergine = '#772953'

# -----------------------
# MODULES
# -----------------------

[aws]
disabled = true
format = 'on [$symbol($profile )[(\($region\) )]($style dimmed)(\[$duration\])]($style) '
# format = '([î‚¶](bgcolor)[$symbol($profile )[(\($region\) )]($style dimmed)(\[$duration\])]($style)[î‚´](bgcolor) )'
# style = 'bold yellow bg:bgcolor'
symbol = 'ï‰° '

[azure]
disabled = true
# format = 'on [$symbol($subscription)]($style) '
# format = '([î‚¶](bgcolor)[$symbol($subscription)]($style)[î‚´](bgcolor) )'
# style = 'bold blue bg:bgcolor'
symbol = 'î¯˜ '

[battery]
format = '[$symbol$percentage ]($style bg:bgcolor1)'

[[battery.display]]
threshold = 100

[character]
format = '$symbol '
# success_symbol = '[ï”](bold green)'
# error_symbol = '[ï”](bold red)'
# success_symbol = '[â¯](bold green)'
# error_symbol = '[â¯](bold red)'

[directory]
truncation_length = 8
truncation_symbol = 'â€¦/'
# style = 'bold cyan italic'
home_symbol = 'ï€• ~'

[docker_context]
only_with_files = false

[fill]
symbol = ' '
style= 'dimmed white'

[gcloud]
disabled = true
format = 'on [$symbol($project )[\($region\)]($style dimmed)]($style) '
# format = 'on [$symbol($account(@$domain) )[(\($region\) \($project\))]($style dimmed)]($style) '
# format = '([î‚¶](bgcolor)[$symbol($account(@$domain) )[(\($region\) \($project\))]($style dimmed)]($style)[î‚´](bgcolor) )'
# style = 'bold blue bg:bgcolor'
symbol = 'ï†  '

[hostname]
ssh_only = false
format = '[[@](bg:bgcolor2)$ssh_symbol$hostname ]($style bg:bgcolor2)'
style = 'bold bright-green'

[kubernetes]
disabled = false
format = '([$symbol$context[( \($namespace\))]($style dimmed)]($style) )'
# format = '([î‚¶](bgcolor)[$symbol$context[( \($namespace\))]($style dimmed bg:bgcolor)]($style)[î‚´](bgcolor) )'
# style = 'bold green bg:bgcolor'
style = 'bold green'
# symbol = 'âˆ '
symbol = 'ï´± '
# symbol = 'â˜¸ï¸'

[kubernetes.context_aliases]
'.*cluster/(.*)' = '$1'

[localip]
# ssh_only = false
disabled = false
# format = '([$localipv4]($style) )'
# format = '([î‚¶](bgcolor)[$localipv4]($style bg:bgcolor)[î‚´](bgcolor) )'
format = '[[\[](bg:bgcolor2)$localipv4[\] ](bg:bgcolor2)]($style bg:bgcolor2)'
style = 'bold bright-purple'

[os]
# format = '[$symbol ]($style)'
format = '[$symbol ]($style bg:bgcolor2)'
style = 'bold ubuntu_orange'
disabled = false

[os.symbols]
Windows = 'î˜ª '
Ubuntu ='ïŒ› '
  
[shell]
disabled = false
fish_indicator = 'ğŸŸ'
bash_indicator = 'î¯Š '
zsh_indicator = 'ğŸš€'
# zsh_indicator = 'ğŸ™‚'
powershell_indicator = 'î¯‡ '
unknown_indicator = 'ïŠœ '
format  = '[$indicator]($style bg:bgcolor2)'

[shlvl]
# disabled = false
# format = '[$symbol]($style)'
# symbol = 'ï”'
# symbol = 'â¯'
symbol = 'ï…‰'
# repeat = true
# threshold = 1

[status]
disabled = false
symbol = 'ïª '
# symbol = 'ï€ '
map_symbol = true
pipestatus = true

[time]
disabled = false
format = '[ï€— $time]($style bg:bgcolor1)'
# style = 'bold bright-yellow'

[username]
show_always = true
format = '[$user]($style bg:bgcolor2)'
style_user = 'bold bright-yellow'
